[package]
name = "abc312"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio={version = "0.4.3" , features = ["derive"]}
petgraph="0.6.3"
itertools = "0.10.5"
superslice = "1.0.0"

[profile.release]
lto = true
panic = 'abort'
