[package]
name = "abc286"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio={version = "0.4.3" , features = ["derive"]}
petgraph="0.5.0"
[profile.release]
lto = true
panic = 'abort'
