[package]
name = "dp"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = {version = "0.4.3" , features = ["derive"]}
itertools = "0.10.5"
[profile.release]
lto = true
panic = 'abort'
